name: Discord Release Notification

on:
  release:
    types: [published]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          RELEASE_NAME="${{ github.event.release.name }}"
          RELEASE_TAG="${{ github.event.release.tag_name }}"
          RELEASE_URL="${{ github.event.release.html_url }}"
          REPO_NAME="${{ github.repository }}"
          
          # Obtener el body del release y procesar el Markdown básico
          RELEASE_BODY=$(echo '${{ github.event.release.body }}' | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | sed 's/`/\\`/g' | sed -E ':a;N;$!ba;s/\r{0,1}\n/\\n/g')
          
          # Convertir algunos elementos de Markdown a formato Discord
          RELEASE_BODY=$(echo "$RELEASE_BODY" | sed 's/\*\(.*\)\*/_\1_/g') # Cursiva
          RELEASE_BODY=$(echo "$RELEASE_BODY" | sed 's/^- /• /g') # Listas

          # Limitar la longitud del body y añadir el enlace "Ver más"
          if [ ${#RELEASE_BODY} -gt 950 ]; then
            RELEASE_BODY="${RELEASE_BODY:0:950}...\n\n[Ver más]($RELEASE_URL)"
          else
            RELEASE_BODY="$RELEASE_BODY\n\n[Ver más]($RELEASE_URL)"
          fi
          
          # Crear el JSON para el embed
          JSON_PAYLOAD=$(cat <<EOF
          {
            "embeds": [{
              "title": "Nueva Versión: $RELEASE_NAME",
              "description": "Se ha publicado una nueva versión en $REPO_NAME",
              "color": 5814783,
              "fields": [
                {
                  "name": "Versión",
                  "value": "$RELEASE_TAG",
                  "inline": true
                },
                {
                  "name": "Detalles",
                  "value": "[Ver en GitHub]($RELEASE_URL)",
                  "inline": true
                },
                {
                  "name": "Notas de Versión",
                  "value": "$RELEASE_BODY"
                }
              ],
              "footer": {
                "text": "Democracy Network - Github"
              },
              "timestamp": "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            }]
          }
          EOF
          )
          
          # Enviar el embed a Discord
          curl -H "Content-Type: application/json" -d "$JSON_PAYLOAD" $DISCORD_WEBHOOK
